require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**'
    - 'db/**'
