require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - 'bin/**'
